CREATE TABLE AudioFile
(
	AudioFileId INT NOT NULL AUTO_INCREMENT,
	Artist VARCHAR(1000) NULL,
	Title VARCHAR(1000) NULL,
	TrackNumber INT NULL,
	Album VARCHAR(1000) NULL,
	Duration INT NULL,
	DeviceUuid VARCHAR(100) NOT NULL,
	RelativePath VARCHAR(2000) NOT NULL,
	LastSeen DATETIME NOT NULL,
	PRIMARY KEY (AudioFileId)
)
